blank_issues_enabled: false
contact_links:
  - name: Development Documentation
    url: https://github.com/velmuruganvelayutham/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: View the development guide for technical information
  - name: Application Help
    url: https://github.com/velmuruganvelayutham/skills-expand-your-team-with-copilot/blob/main/README.md
    about: General information about the Mergington High School Management System